apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-record-service
      env: green
  template:
    metadata:
      labels:
        app: patient-record-service
        env: green
    spec:
      containers:
      - name: patient-record-service
        image: ranaliw/patient-record-service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: patient-record-service-green
spec:
  selector:
    app: patient-record-service
    env: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

