name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ranaliw/patient-record-service:${{ github.sha }} .
        docker push ranaliw/patient-record-service:${{ github.sha }}

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/patient-record-service-blue patient-record-service=ranaliw/patient-record-service:${{ github.sha }} --record
