name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ranaliw/patient-record-service:${{ github.sha }} .
        docker push ranaliw/patient-record-service:${{ github.sha }}
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        cat <<EOF > ~/.kube/config
        apiVersion: v1
        clusters:
        - cluster:
            certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZmlmQWFueFZnM1V3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeU1qSXdOekE1TkRSYUZ3MHpOREV5TWpBd056RTBORFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURLYU9RSlNDN3lxS3NTOGt5RnFSSXZYUm53aXRqN25tMmU0UmRmWm9EblVXTTV6NzRkYmtKcklmVjAKVUhzc2hRZEJBNUx3VTVYYTVoSEFkeGE4TjBaaU5LSW5GYkpZM3hpV0hBSEs2OWtCSzNvWjlKUnoxa2EvMGs4dAp0Mm13RjR6ZzNyNSt0TXNJREhTM1p0cGlISjBVQ0Rvb29wYjlrSU9IOEZnaFdMRXNBajBxZjZUWUt6RExsZktQCmhzRVhQcVovN0VLNDVQTzhjTXgzMXlTbURxM0RRU2lBL1RhTENyOFBKMUtlejJ3MUZIL3MzblA1MTIzcEdveUUKMi9PbyttYmxPM3Robm9kc0tyL2FNZzI2UTVQYnd0TGdQRzNOTmFvMWZta2V0SXBrdlhGTHJuM0NBcWc2Qk1zQgpaYmFuQW1GTWJ6MXZKYUdDMStSODVqS2FwUS9KQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRV01aWlNQTitBbkZtQ1dmTWpnbDBDY3FtdWVUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2JIdzRZSnhBSApnSm9OZU1ZWFVnN0tJS2xvd0hORXl1YVNSU0VDb2diTGFFT2lKbEY2YWdiRmZUdkhBWm5nQ013U25GTlAva2xTCklMRVc0R294ejRXc2VNdVNvTHIyMzBpWFlIOExqL1BjY2ZYZllXSXJjWkxoTUNURmN4RXFJUWxKaENlOGtpS2oKaHV0N0VweTRKS2RBaTZIUmdObUxYbkxoZmptVDJwT2d6aDQxdFV5VCtzVVVXRXoxNWtjMndPdDhacmFNbUhYdwpIdExFK3JEUmc2d3VMM0NRVzFldUtjL0RLdDJrUWFPM2VDeUZXTld6M2hVSWRQMG1uclZUTkFhMWM4VDFnZnZMCkV6S1BVRDBFZzd1TVR1cnRqd3VuSUE2V21ORGR0OUVIREZqcm8wRmNXMHhlOTM3b2E5aTk3eUVvN2RhOXFoSTUKN3F5dms4bTc1QVppCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            server: https://8F46DB8E5E98BB943BB8426939504FAA.gr7.us-east-1.eks.amazonaws.com
          name: HealthSyncCluster.us-east-1.eksctl.io
        - cluster:
            certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJV0xEcTBzK2t4Rjh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeU1Ua3hNelE1TVRGYUZ3MHpOREV5TVRjeE16VTBNVEZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMxSkhaanZaeFNxRUdneWJLMDk3bUE0emF2TzRtMHlHMkdVWWt4RDFQWGNWRGFxOWJKVEZlcXJlYW0KbXFWODRxbldVYzBMcXYvdytadXJYZWE2SkdaTDZUSEx5cEx4VFJiYmFPQXd2SHEvNjVOQXhLMHVSbWd2U2F4NApXRFg4MkJsTDVLMWUyRnkwaGl6Z0tZaG5GODFJblE2Z1hWUWtoYVo2NlFoNXpFTElIOFlzTEczSVpYbDdraTc0ClhkZXRrNFJVWVFxQ1JnMEQyaCtGbUVKbERtTC9xemptZmlYcUFWdEpHcFFYak1EZ1ZJc1Q1VjJMenViSHllcUUKTXBPeEczYU05S1JHRzV1cUV0aUI4T1FjSHo1UnhKOTdLSUt2a0x0bG9RWmlaM3d0QzBTWkREdTdiaFFzYUh2Ygp3dlQxZXo5QlRENEJicG5tMWg5alRmVDk0NTAxQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTSzdJU2dFNnFweW9jQ1NqcWJaZ1c4bTFEc2FEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQW1lUjZuU09hNQpDeHljcEZHQTNlZUtiYm0vTVF0R29DaXdzL3FXT0JzdXdwYmQrRXNJTDdST1ZuNi8xZnM5aXNuSmxKZ2krSFJOCm5IMzI1K3ZjdWZ6Rkc1V0JkNkcrdjRSY3lJd3VTbTkvZE5ISWtjcVovOHJuZGx1NW9ZQ1F2RGtYUTFKK3pYbGcKWjhybUplNGtqVlRDMC9NVmhyZE0zRnpEbGsrc1VFeEJHQ2pOZEJpSlc0ZW5kaWkvTXpOcTVROEZ4aVJHdFRSNgpyVjlOS1BGYWJueExSaXkrUWhmcnQ5RVN1TEp2bkU2ZkwzT3FJR2NXY0djQWt3R2JiUnArT0JZYWd0Zzl0cjJXCnhScXA1eFZNemVPM2wrUHFXRUIwaUhjaWNsYnI2MmR0MmZCZzhjdVJwS2FWMnovQkg2THlrZEd4Y2daOW8rTDEKakxSclB3aTEydXp1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            server: https://kubernetes.docker.internal:6443
          name: docker-desktop
        - cluster:
            certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZmlmQWFueFZnM1V3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeU1qSXdOekE1TkRSYUZ3MHpOREV5TWpBd056RTBORFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURLYU9RSlNDN3lxS3NTOGt5RnFSSXZYUm53aXRqN25tMmU0UmRmWm9EblVXTTV6NzRkYmtKcklmVjAKVUhzc2hRZEJBNUx3VTVYYTVoSEFkeGE4TjBaaU5LSW5GYkpZM3hpV0hBSEs2OWtCSzNvWjlKUnoxa2EvMGs4dAp0Mm13RjR6ZzNyNSt0TXNJREhTM1p0cGlISjBVQ0Rvb29wYjlrSU9IOEZnaFdMRXNBajBxZjZUWUt6RExsZktQCmhzRVhQcVovN0VLNDVQTzhjTXgzMXlTbURxM0RRU2lBL1RhTENyOFBKMUtlejJ3MUZIL3MzblA1MTIzcEdveUUKMi9PbyttYmxPM3Robm9kc0tyL2FNZzI2UTVQYnd0TGdQRzNOTmFvMWZta2V0SXBrdlhGTHJuM0NBcWc2Qk1zQgpaYmFuQW1GTWJ6MXZKYUdDMStSODVqS2FwUS9KQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRV01aWlNQTitBbkZtQ1dmTWpnbDBDY3FtdWVUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2JIdzRZSnhBSApnSm9OZU1ZWFVnN0tJS2xvd0hORXl1YVNSU0VDb2diTGFFT2lKbEY2YWdiRmZUdkhBWm5nQ013U25GTlAva2xTCklMRVc0R294ejRXc2VNdVNvTHIyMzBpWFlIOExqL1BjY2ZYZllXSXJjWkxoTUNURmN4RXFJUWxKaENlOGtpS2oKaHV0N0VweTRKS2RBaTZIUmdObUxYbkxoZmptVDJwT2d6aDQxdFV5VCtzVVVXRXoxNWtjMndPdDhacmFNbUhYdwpIdExFK3JEUmc2d3VMM0NRVzFldUtjL0RLdDJrUWFPM2VDeUZXTld6M2hVSWRQMG1uclZUTkFhMWM4VDFnZnZMCkV6S1BVRDBFZzd1TVR1cnRqd3VuSUE2V21ORGR0OUVIREZqcm8wRmNXMHhlOTM3b2E5aTk3eUVvN2RhOXFoSTUKN3F5dms4bTc1QVppCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            server: https://8F46DB8E5E98BB943BB8426939504FAA.gr7.us-east-1.eks.amazonaws.com
          name: arn:aws:eks:us-east-1:515966519083:cluster/HealthSyncCluster
        contexts:
        - context:
            cluster: docker-desktop
            user: docker-desktop
          name: docker-desktop
        - context:
            cluster: HealthSyncCluster.us-east-1.eksctl.io
            user: iamuser_cc@HealthSyncCluster.us-east-1.eksctl.io
          name: iamuser_cc@HealthSyncCluster.us-east-1.eksctl.io
        - context:
            cluster: arn:aws:eks:us-east-1:515966519083:cluster/HealthSyncCluster
            user: arn:aws:eks:us-east-1:515966519083:cluster/HealthSyncCluster
          name: arn:aws:eks:us-east-1:515966519083:cluster/HealthSyncCluster
        current-context: arn:aws:eks:us-east-1:515966519083:cluster/HealthSyncCluster
        kind: Config
        preferences: {}
        users:
        - name: docker-desktop
          user:
            client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRakNDQWlxZ0F3SUJBZ0lJTlgwcUsxNThZajR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeU1Ua3hNelE1TVRGYUZ3MHlOVEV5TVRreE16VTBNVE5hTURZeApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sc3dHUVlEVlFRREV4SmtiMk5yWlhJdFptOXlMV1JsCmMydDBiM0F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3hVM2pzcVBkejRDckcKZGl3aTVlYUk0T2NIT2F3UmtEajAweURUM0Z2eTJFWUpJdGhMaTN4bmEwaXJlZFRmYWs1aUcvWHQ0dENhQWp4QgoyRkdFTzRSYkMxTXdtYW5mN1JYVVJWKzhoeFA5eTFUdjBjVEdJcnNXKzlLcXJ5N0ZjOVBvTEdZRkpSNmVoaitoCnZRMTZubmpIbDFRbXViM0VxVHJXdG1uNmQ1SFkzQk5GSFNkU2lCY1d2M0JqcnhzNC9oL3RqVlVpYkxXT3hDck4KMThSS2ZPblRUUkQ1R0VWUElGNDV2VnZUNGk0dlZhbGY1cUQxamVyQTJkRGYzNkdVaHZtbERSSTRDSDRTSFZQZgp4QTVXRjJmTmxSSDFvamJJZ3crOFN1SDBKSU1EcVBGNHRhY0FwMmlnWmpDLzJnOUVDeHFqb2RKemJkTjB2OUxECktPYXdKVHVmQWdNQkFBR2pkVEJ6TUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUI4R0ExVWRJd1FZTUJhQUZJcnNoS0FUcXFuS2h3SktPcHRtQmJ5YgpVT3hvTUIwR0ExVWRFUVFXTUJTQ0VtUnZZMnRsY2kxbWIzSXRaR1Z6YTNSdmNEQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBT3JSSlBldnc0VUQzTVBwdm42cE8rZHBVMTBXWUpEeEpoOTF1akdzdnROZ2wxbldXKzlwNFZ4bHYKRzM1WXdSbm84bFJBVzJHV1lhcWtMSDFCQXJxdmoxRnY3QU1KZFhMM2VQTHZVcURMR1Zpb0J5aituRi9sRXc5TgpWNTNYNjlnL3o2eDRCNnFjMmVXelZhN28vbU9iTEVSNUhaQmk0NWNvZ3hxenFycEVGNlgxTlp1WGxoMHBLY2pSCk5sL3hsM1Yxc1FZamhCbTJ2R0xrMHo1WTVtNm9SSkY4YU1aV09HaFVmaWRjeml5NW5JQXU2NGRBSUUvdzNkVFAKcTU3RzR1dzFVaklQWHRXZEo0VFN0MHVTdHkvc293ZUdma1B5V3pXdHV3cHc4NG1hQzdTN0Zsd2lKS0pxcUJmaQo3WG81UGNYREYxNlRWZkhQNUZFdDg0dE8yRlNjN0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
            client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBc1ZONDdLajNjK0FxeG5Zc0l1WG1pT0RuQnptc0VaQTQ5Tk1nMDl4Yjh0aEdDU0xZClM0dDhaMnRJcTNuVTMycE9ZaHYxN2VMUW1nSThRZGhSaER1RVd3dFRNSm1wMyswVjFFVmZ2SWNUL2N0VTc5SEUKeGlLN0Z2dlNxcTh1eFhQVDZDeG1CU1Vlbm9ZL29iME5lcDU0eDVkVUpybTl4S2s2MXJacCtuZVIyTndUUlIwbgpVb2dYRnI5d1k2OGJPUDRmN1kxVklteTFqc1FxemRmRVNuenAwMDBRK1JoRlR5QmVPYjFiMCtJdUwxV3BYK2FnCjlZM3F3Tm5RMzkraGxJYjVwUTBTT0FoK0VoMVQzOFFPVmhkbnpaVVI5YUkyeUlNUHZFcmg5Q1NEQTZqeGVMV24KQUtkb29HWXd2OW9QUkFzYW82SFNjMjNUZEwvU3d5am1zQ1U3bndJREFRQUJBb0lCQUdmenFoajZlSTNLWk9rUgpENUNwdTNxVWRYcnIyUzQyb04wTkE5cU8vS3doRXZWNkl0Z3VmaEJXZVRSazZHRE1mZ1RQcFZ6K01SR0hxL0ZoCnNXL1dRQ0hyUXFwaitvelYvSTBDMmp1MzZBVkk5SkxlSXYrUURxTkxudFVHZTJHdkpCT2dLM0pxcjBkNUpjWlkKQUpYWVhxK0t5LzhqdGRhYTZtNUNZMkE4UmhpYytSN0NteGt5V09JTlBUL3NuTjVuQitrWlFZZXpnS2l6MU1jbgp4ZXoyOXZBQ1o3Vmx4dEZackE1OGhaa2tpTTVIaVJObXozYnBDRWZkeTM3dlZkOVpvSXJneDkvRlY2M1dBd2oyCkkyMUVXYVlTcW83YVJkbE1uZERvTEN0UFFmOWRWSjM2NURQWk5pMFNJSjJ6TDhsa3p1SHlibC9VdlYyRkM0ZHAKTWJFVjhGa0NnWUVBejQ0bCs5VkhzUWg2SmlXYnI0eG5VTCtqUnVnRG1lcHMxNzhnOWwycEYremJmRm5xeENzTQo1UDk4THhOM09HUGR1TDhVdDB0QVN1bTM5bWpnWGhvSkZ1NjZtam4wWE5aZG1RdG5sQ0hLLzNVMVRkbXNmSzRiCitPbUQ2Nm1ONUlEWFRLTXdEWDRhOFFuVXBpb2o0Q1hIejl1TGx5eDk0Y0QyaEJ3ZklRU01HbE1DZ1lFQTJyY1IKT1g4NlJKQWdKeTNDR0hZLy96QWxPTnhXUDR5cmFBT01uSVNaaDRmTk1uVlYwUUFrMTV6MlBxRzJUWjZIU2p6VQppRWd1aWRvWEhBK1RlbXVKS3RwbThtaUMzWWhKVmY0eFZndlFOYWtxVkFxTXMyK2Fwa2crN2NyWGtLUHd1b2NtCmpWZ3BCZGxtYkwyZ1pmUXhhMHMybEg5MGlZZzM4RmZBcVRXTmFBVUNnWUVBZ09DdEtVQjM4YTluMllRRXRlNmkKd0hzZWNZcmpvWkQwNE1wbk4xTlZDZXdqSllYWHh0Tk1nRzA3dVNlSElkYXcrR1IrQW9xUmMzTElyaExWTHRsUAp4NU9ZL3ViNW15UG9ubjE4WlhqT1NlMkhtYjJONHlWaGJSL2lzRlJxTFBicnVVU2pNOTJYOFErL29TWU5mTU00CjNSSmdEUkN0WVo2bDg4WmFkZkFTNXMwQ2dZQjA5d0lYSlpzYm41Z1NXNzQ1SnNRQ3pOU2JHL3BqOGU2WXFZMUIKQndpMEdrUDZnQlZzdUE3NzM4MHdvWHJFOThxU1FRWEgvQkluVnFLVk54OC9rTkxDUUJwZCtOWkRjdWNGUGZOVQplT3pZUmFlRldqNzBsdksxaWwxYy9lVmFUTklvYnE2SFdHWlg0bk9NSTd6cnlUUEVsV3lTN2JaODlvUXozRG9FClE4ZGpvUUtCZ0JrdWFzdDhkMkVVeFRPQll6ZkJIdVRUU3c2ZnNLS0NJSkFyVTNub09CTGY0eU5mVCsvNyt0V1oKdFJDRXB0Z09CWjZFVkoyOE81UTVuazArZ1p5UkMxMFVNYVFlTk5uQUhKOEo2UjYwdGhaNWtxVWk3bmlIRENkWgpHR0ozdExsRWNyZ0FuRlltQ3R0T3FqUHhISDdaeXNIQm9YRUx6MUs3UWtrYk9WbnhpeU5ZCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
        - name: iamuser_cc@HealthSyncCluster.us-east-1.eksctl.io
          user:
            exec:
              apiVersion: client.authentication.k8s.io/v1beta1
              args:
              - eks
              - get-token
              - --output
              - json
              - --cluster-name
              - HealthSyncCluster
              - --region
              - us-east-1
              command: aws
              env:
              - name: AWS_STS_REGIONAL_ENDPOINTS
                value: regional
              provideClusterInfo: false
        - name: arn:aws:eks:us-east-1:515966519083:cluster/HealthSyncCluster
          user:
            exec:
              apiVersion: client.authentication.k8s.io/v1beta1
              args:
              - --region
              - us-east-1
              - eks
              - get-token
              - --cluster-name
              - HealthSyncCluster
              - --output
              - json
              command: aws
        EOF

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/patient-record-service-blue patient-record-service=ranaliw/patient-record-service:${{ github.sha }}
